[project]
name = "eowautomater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gitpython>=3.1.43",
    "langchain-google-genai>=2.0.7",
    "langchain>=0.3.12",
    "pydantic>=2.10.3",
]
